version: "3.9"
services:
 useritem-api-service:
  image: jarne-drijbooms/project-api2
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
